[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "MojoTensor"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.2.0.dev2026020616,<0.27"
